---
title: "Research"
editor: visual
---

## Research Interests
1. Collaborative Governance
2. Nonprofit Management and Leadership
3. Diversity, Equity, Inclusion, and Justice

## Research in Progress

### Dissertation

Collaborative Governance and Cognitive Dissonance in Comparative Race and Immigration Policy

How does cognitive dissonance in 21st century American immigration policy impact collaborative governance related to refugee resettlement?

### Book Chapter (pending publication)

Women Falling through the Cracks: Intersectionality During Crisis and Implications for Human Resources Management

This book chapter use an intersectional perspective to explore COVID-19's impact on women in the workforce. We look at race, socioeconomic status, and gender. We also apply these lenses to various sectors. At the end, we provide insight for human resource management.

### Conceptual Paper

Cognitive Dissonance in Decision-making During Crisis 

In this conceptual paper, I investigate the impact of cognitive dissonance on equitable decision-making 
during crisis.  Cognitive dissonance, according to the seminal literature, is the psychological discomfort experienced when plans or beliefs are countered by newly discovered facts.  A person must then decide how to rectify this dissonance by either changing their previous belief or rationalizing a dismissal of the new information.  Dissonance, though heavily studied in psychology, has not been thoroughly researched in public administration.  In the public sector, decisions are very important because they heavily impact the lives of the public.  Therefore, if cognitive dissonance impacts equitable decision-making, then this angle needs to be further studied.  Viewing equity as the foundational belief and as a pillar of our field, I look at case studies in which public administrators made decisions during crisis, and I examine whether dissonance played a role in their decision-making.